/** @format */

import { Inter } from "next/font/google";
import "./globals.css";
import { AuthUserProvider } from "@/firebase/authContext";
import { MessageProvider } from "../firebase/storeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Facebook",
  description: "Generated by Facebook",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <AuthUserProvider>
            <MessageProvider>{children}</MessageProvider>
          </AuthUserProvider>
        </main>
      </body>
    </html>
  );
}
